
tree = BinTree("F")
tree.root.left = Node("B")
tree.root.left.left = Node("A")
tree.root.left.right = Node("D")
tree.root.left.right.left = Node("C")
tree.root.left.right.right = Node("E")
tree.root.right = Node("G")
tree.root.right.right = Node("I")
tree.root.right.right.left = Node("H")

tree = BinTree(1)
tree.root.left = Node(2)
tree.root.left.left = Node(3)
tree.root.left.right = Node(4)
tree.root.left.right.left = Node(5)
tree.root.left.right.right = Node(6)
tree.root.right = Node(7)
tree.root.right.right = Node(8)
tree.root.right.right.left = Node(9)